[project]
name = "fastapi-for-data-science"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.129.0",
    "ruff>=0.15.1",
    "sqlalchemy[asyncio,mypy]>=2.0.46",
]
